name: Notify Doc Repo
  on:
    push:
      branches:
        - test-github-action
  jobs:
    notify:
     runs-on: ubuntu-latest
     steps:
      - name: Trigger workflow in doc repository
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.MAIN_REPO_TOKEN }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            "https://api.github.com/repos/mmm-mmm-mmz/qubes-doc-rtd-old/dispatches" \
            -d '{"event_type":"submodule_update"}'
    

